try:
    from .version import version as __version__  # noqa
except ImportError:  # pragma: no cover
    raise ImportError(
        "Failed to find (autogenerated) version.py. "
        "This might be because you are installing from GitHub's tarballs, "
        "use the PyPI ones."
    )
